begin;

-- ============================================================
-- SIGNAL / joinv2
-- 0006_signal_production_catalog.sql
--
-- Purpose:
--   Seed the first clean production catalog authority for SIGNAL.
--
-- Production hierarchy:
--   Florida
--     -> Tampa
--       -> Going Out
--         -> Drinks
--         -> Sports
--         -> Creative
--         -> Food
--         -> Live Music
--         -> Outdoors
--         -> Chill
--         -> Explore
--         -> Nightlife
--
-- Important:
--   - Existing __g414_b3__ fixtures are NOT modified.
--   - No fixture UUID is reused.
--   - Production UUIDs are generated by PostgreSQL.
--   - Tampa timezone authority is America/New_York.
--   - Drinks and Nightlife require age 21.
--   - Remaining V1 activities require age 18.
--   - Activity category is organizational taxonomy only.
--   - Formation behavior is NOT changed here.
-- ============================================================

-- ------------------------------------------------------------
-- 1. PRODUCTION STATE
-- ------------------------------------------------------------

insert into public.states (
  code,
  name,
  is_active
)
values (
  'FL',
  'Florida',
  true
)
on conflict (code)
do update set
  name = excluded.name,
  is_active = excluded.is_active;

-- ------------------------------------------------------------
-- 2. PRODUCTION CITY
-- ------------------------------------------------------------

insert into public.cities (
  state_id,
  name,
  slug,
  latitude,
  longitude,
  timezone_name,
  is_active
)
select
  s.id,
  'Tampa',
  'tampa',
  27.9506,
  -82.4572,
  'America/New_York',
  true
from public.states s
where s.code = 'FL'
on conflict (slug)
do update set
  state_id = excluded.state_id,
  name = excluded.name,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  timezone_name = excluded.timezone_name,
  is_active = excluded.is_active;

-- ------------------------------------------------------------
-- 3. PRODUCTION ACTIVITY CATEGORY
-- ------------------------------------------------------------

insert into public.activity_categories (
  name,
  slug,
  sort_order,
  is_active
)
values (
  'Going Out',
  'going-out',
  10,
  true
)
on conflict (slug)
do update set
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;

-- ------------------------------------------------------------
-- 4. PRODUCTION ACTIVITIES
-- ------------------------------------------------------------

with production_category as (
  select id
  from public.activity_categories
  where slug = 'going-out'
),
production_activities (
  name,
  slug,
  minimum_age
) as (
  values
    ('Drinks',     'drinks',     21),
    ('Sports',     'sports',     18),
    ('Creative',   'creative',   18),
    ('Food',       'food',       18),
    ('Live Music', 'music',      18),
    ('Outdoors',   'outdoors',   18),
    ('Chill',      'chill',      18),
    ('Explore',    'explore',    18),
    ('Nightlife',  'nightlife',  21)
)
insert into public.activities (
  category_id,
  name,
  slug,
  minimum_age,
  is_active
)
select
  pc.id,
  pa.name,
  pa.slug,
  pa.minimum_age,
  true
from production_category pc
cross join production_activities pa
on conflict (slug)
do update set
  category_id = excluded.category_id,
  name = excluded.name,
  minimum_age = excluded.minimum_age,
  is_active = excluded.is_active;

commit;
